version: '3.3'

services:
  database:
    container_name: studentdb
    hostname: studentdb
    image: mst619/studentdbfinal
    restart: always
    networks:
      - etiasgn2
    environment:
      # MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_PASSWORD: password
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  web:
    container_name: web
    hostname: web
    image: mst619/studenthtmlfinal
    restart: always
    ports:
      - "80:80"
  student:
    depends_on: 
      - database
    image: mst19/studentfinal
    container_name: student-server
    hostname: student-server
    ports:
      - 8103:8103
    networks:
      - etiasgn2
    deploy:
      restart_policy:
        condition: on-failure


networks:
  etiasgn2:
    driver: bridge