version: '3.3'

services:
  database:
    container_name: studentdbtest
    hostname: studentdbtest
    image: mysql:latest
    restart: always
    networks:
      - etiasgn2
    environment:
      # MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_PASSWORD: password
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  web:
    container_name: studentwebtest
    hostname: studentwebtest
    build:
      context: ./HTML
    restart: always
    ports:
      - "80:80"
  student:
    depends_on: 
      - database
    build:
      context: ./Student
    container_name: studenttest-server
    hostname: studenttest-server
    ports:
      - 8104:8104
    networks:
      - etiasgn2
    deploy:
      restart_policy:
        condition: on-failure


networks:
  etiasgn2:
    driver: bridge